import { describe, expect, it, vi } from 'vitest';
import { handle, materializeResponse } from './hooks.server';

describe('security headers hook', () => {
	it('adds the WebMCP-compatible security baseline', async () => {
		const response = await handle({
			event: {} as never,
			resolve: async () => new Response('ok')
		});

		expect(response.headers.get('Origin-Agent-Cluster')).toBe('?1');
		expect(response.headers.get('Permissions-Policy')).toBe('tools=(self)');
		expect(response.headers.get('X-Content-Type-Options')).toBe('nosniff');
		expect(response.headers.get('Referrer-Policy')).toBe('strict-origin-when-cross-origin');
		expect(response.headers.get('Content-Security-Policy')).toContain("script-src 'self'");
		expect(response.headers.get('Content-Security-Policy')).toContain("frame-ancestors 'self'");
		expect(response.headers.get('Content-Security-Policy')).not.toContain("script-src 'self' 'unsafe-inline'");
	});

	it('preserves the nonce-aware CSP generated by SvelteKit', async () => {
		const existing = "script-src 'self' 'nonce-test'; object-src 'none'";
		const response = await handle({
			event: {} as never,
			resolve: async () => new Response('ok', { headers: { 'Content-Security-Policy': existing } })
		});

		expect(response.headers.get('Content-Security-Policy')).toBe(existing);
	});

	it('fails closed when D1 has no ready publication', async () => {
		const resolve = vi.fn(async () => new Response('should not run'));
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/api/v1/meta'),
				route: { id: '/api/v1/meta' },
				locals: {},
				platform: {
					env: {
						DB: {
							prepare: () => ({ first: async () => null })
						}
					}
				}
			} as never,
			resolve
		});

		expect(response.status).toBe(503);
		expect(await response.json()).toMatchObject({
			liveData: { state: 'degraded', reason: 'publication_barrier_closed' }
		});
		expect(resolve).not.toHaveBeenCalled();
		expect(response.headers.get('Cache-Control')).toBe('no-store');
	});

	it('serves the recorded workspace without D1 only when the server flag is enabled', async () => {
		const resolve = vi.fn(async () => new Response('recorded workspace'));
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/workspace?demo=recorded'),
				route: { id: '/workspace' },
				locals: {},
				platform: {
					env: {
						ALLOW_RECORDED_DEMO: 'true',
						DB: {
							prepare: () => { throw new Error('recorded workspace must not read D1'); }
						}
					}
				}
			} as never,
			resolve
		});

		expect(response.status).toBe(200);
		expect(await response.text()).toBe('recorded workspace');
		expect(resolve).toHaveBeenCalledOnce();
	});

	it('keeps the privacy page available when no data release is published', async () => {
		const resolve = vi.fn(async () => new Response('privacy page'));
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/privacy'),
				route: { id: '/privacy' },
				locals: {},
				platform: {
					env: {
						DB: {
							prepare: () => { throw new Error('privacy must not require a publication'); }
						}
					}
				}
			} as never,
			resolve
		});

		expect(response.status).toBe(200);
		expect(await response.text()).toBe('privacy page');
		expect(resolve).toHaveBeenCalledOnce();
	});

	it('keeps the recorded workspace behind the publication barrier when the server flag is disabled', async () => {
		const resolve = vi.fn(async () => new Response('should not run'));
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/workspace?demo=recorded'),
				route: { id: '/workspace' },
				locals: {},
				platform: {
					env: {
						ALLOW_RECORDED_DEMO: 'false',
						DB: {
							prepare: () => ({ first: async () => null })
						}
					}
				}
			} as never,
			resolve
		});

		expect(response.status).toBe(503);
		expect(resolve).not.toHaveBeenCalled();
	});

	it('validates the same D1 generation after the complete request', async () => {
		const validate = vi.fn(async () => ({ valid: 1 }));
		const event = {
			url: new URL('https://bankgraph.example/api/v1/meta'),
			route: { id: '/api/v1/meta' },
			locals: {},
			platform: {
				env: {
					DB: {
						prepare: (sql: string) => sql.includes('SELECT 1 AS valid')
							? { bind: () => ({ first: validate }) }
							: { first: async () => ({ release: '20260630', generation: 'generation-1' }) }
					}
				}
			}
		};
		const response = await handle({ event: event as never, resolve: async () => new Response('ok') });

		expect(response.status).toBe(200);
		expect(event.locals).toMatchObject({
			liveDataRelease: '20260630',
			liveDataGeneration: 'generation-1'
		});
		expect(validate).toHaveBeenCalledOnce();
	});

	it('discards a rendered response when its D1 generation cannot be validated', async () => {
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/api/v1/meta'),
				route: { id: '/api/v1/meta' },
				locals: {},
				platform: {
					env: {
						DB: {
							prepare: (sql: string) => sql.includes('SELECT 1 AS valid')
								? { bind: () => ({ first: async () => null }) }
								: { first: async () => ({ release: '20260630', generation: 'generation-1' }) }
						}
					}
				}
			} as never,
			resolve: async () => new Response('{"mixed":true}', {
				headers: { 'Content-Type': 'application/json' }
			})
		});

		expect(response.status).toBe(503);
		expect(await response.json()).toMatchObject({
			liveData: { reason: 'publication_barrier_unavailable' }
		});
	});

	it('waits for a lazy response body before the post-render generation check', async () => {
		let bodyFinished = false;
		const validate = vi.fn(async () => {
			expect(bodyFinished).toBe(true);
			return { valid: 1 };
		});
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/api/v1/meta'),
				route: { id: '/api/v1/meta' },
				locals: {},
				platform: {
					env: {
						DB: {
							prepare: (sql: string) => sql.includes('SELECT 1 AS valid')
								? { bind: () => ({ first: validate }) }
								: { first: async () => ({ release: '20260630', generation: 'generation-1' }) }
						}
					}
				}
			} as never,
			resolve: async () => new Response(new ReadableStream<Uint8Array>({
				async start(controller) {
					await Promise.resolve();
					controller.enqueue(new TextEncoder().encode('complete'));
					bodyFinished = true;
					controller.close();
				}
			}))
		});

		expect(await response.text()).toBe('complete');
		expect(validate).toHaveBeenCalledOnce();
	});

	it('rejects a dynamic body that exceeds the bounded materialization limit', async () => {
		await expect(materializeResponse(new Response('12345'), 4)).resolves.toBeNull();
	});

	it('keeps only checksum-addressed lake exports outside the dynamic D1 fence', async () => {
		const response = await handle({
			event: {
				url: new URL('https://bankgraph.example/api/v1/fdic/sod/export?year=2024'),
				route: { id: '/api/v1/fdic/sod/export' },
				locals: {},
				platform: {
					env: {
						DB: {
							prepare: () => { throw new Error('immutable export must not take the hot-data fence'); }
						}
					}
				}
			} as never,
			resolve: async () => new Response(new ReadableStream<Uint8Array>({
				start(controller) {
					controller.enqueue(new TextEncoder().encode('immutable-parquet-bytes'));
					controller.close();
				}
			}))
		});

		expect(response.status).toBe(200);
		expect(await response.text()).toBe('immutable-parquet-bytes');
	});
});
